const app=document.getElementById('app');
const canvas=document.getElementById('saveCanvas');

const profiles=[
 {angel:'АРХАНГЕЛ МИХАИЛ',seal:'М',tone:'защиты и внутренней силы',voice:'Твоя сила сегодня не требует доказательств. Она проявляется в спокойном выборе оставаться на своей стороне.',themes:['ЗАЩИТА','ВНУТРЕННЯЯ ОПОРА','СМЕЛОСТЬ','ГРАНИЦЫ','РЕШЕНИЕ','ВОЗВРАЩЕНИЕ К СЕБЕ','СИЛА БЕЗ БОРЬБЫ','БЕЗОПАСНОСТЬ ВНУТРИ','ВЕРНОСТЬ СЕБЕ']},
 {angel:'АРХАНГЕЛ ГАВРИИЛ',seal:'Г',tone:'ясного слова и тонких знаков',voice:'Не торопись искать ответ громче. Сегодня он может прийти через одну фразу, встречу или внутреннее узнавание.',themes:['ГОЛОС','ЗНАК','НОВАЯ ВЕСТЬ','ЯСНОЕ СЛОВО','ТВОРЧЕСКИЙ ПОТОК','РАЗГОВОР','ПРИЗНАНИЕ','СВОЁ ПОСЛАНИЕ','ОТКРЫТАЯ ДВЕРЬ']},
 {angel:'АРХАНГЕЛ УРИИЛ',seal:'У',tone:'ясности и земной мудрости',voice:'Тебе не нужно видеть весь путь. Достаточно заметить тот шаг, после которого внутри становится чуть тише и яснее.',themes:['ЯСНОСТЬ','ЗЕМНАЯ МУДРОСТЬ','ВОЗМОЖНОСТЬ','ПОРЯДОК','РЕСУРС','СЛЕДУЮЩИЙ ШАГ','ФОКУС','ПРАКТИЧНОЕ ЧУДО','ТОЧКА ОПОРЫ']},
 {angel:'АРХАНГЕЛ РАФАИЛ',seal:'Р',tone:'восстановления и мягкости',voice:'Твоё тело не мешает тебе. Оно честно показывает, где сегодня важнее бережность, пауза и возвращение к своему ритму.',themes:['ВОССТАНОВЛЕНИЕ','МЯГКОСТЬ','ДЫХАНИЕ','ОБНОВЛЕНИЕ','ЗАБОТА','СПОКОЙСТВИЕ','ТИХОЕ ИСЦЕЛЕНИЕ','ТЕЛО ЗНАЕТ','НОВЫЙ РИТМ']},
 {angel:'АРХАНГЕЛ ЧАМУИЛ',seal:'Ч',tone:'любви и живого контакта',voice:'Любовь начинается не с идеальной близости, а с того, как ты обращаешься с собой и что позволяешь входить в своё сердце.',themes:['ЛЮБОВЬ','БЛИЗОСТЬ','ПРИТЯЖЕНИЕ','СЕРДЦЕ','ВСТРЕЧА','ТЕПЛО','САМОЦЕННОСТЬ','НЕЖНОСТЬ']},
 {angel:'АРХАНГЕЛ ИОФИИЛ',seal:'И',tone:'красоты и внутреннего света',voice:'Красота, лёгкость и удовольствие не отвлекают тебя от жизни. Иногда именно они возвращают тебя в неё целиком.',themes:['КРАСОТА','ВДОХНОВЕНИЕ','ЛЁГКОСТЬ','ВЗГЛЯД','ЦЕННОСТЬ','УДОВОЛЬСТВИЕ','ИЗОБИЛИЕ','ЭЛЕГАНТНОСТЬ ВЫБОРА']},
 {angel:'АРХАНГЕЛ ЗАДКИИЛ',seal:'З',tone:'освобождения и перехода',voice:'Ты не обязана отвечать новой жизнью на старые условия. Что-то уже завершилось, и твоя энергия может вернуться в настоящее.',themes:['ОСВОБОЖДЕНИЕ','ПРОЩЕНИЕ','НОВОЕ','ТРАНСФОРМАЦИЯ','ОТПУСКАНИЕ','ПЕРЕХОД','НОВАЯ ВЕРСИЯ','ЧИСТОЕ ПРОСТРАНСТВО']}
];
const openings=['Сегодня не нужно торопить события и пытаться заранее понять весь смысл происходящего.','Внутри тебя уже есть больше ясности, чем кажется в моменте, когда мыслей становится слишком много.','Этот день просит не большого рывка, а более тонкого внимания к тому, что отзывается первым.','Иногда важное начинается не с действия, а с момента, когда ты перестаёшь идти против собственного ощущения.','Сейчас полезно оставить немного пространства между вопросом и ответом, чтобы услышать не тревогу, а себя.','То, что предназначено для тебя сегодня, не требует внутренней гонки и доказательств.','Возможно, ты слишком долго смотрела на ситуацию только через разум, хотя тело уже давно подсказывает направление.','Сегодня тебе не нужно становиться сильнее, правильнее или собраннее, чтобы сделать верный шаг.','Есть моменты, когда лучший ответ приходит после того, как внутри становится чуть тише.','Твой день может измениться не из-за большого события, а из-за одного точного выбора в свою пользу.'];
const middles=['Не сравнивай свой путь с чужим темпом. У тебя есть право двигаться так, чтобы не терять себя по дороге.','Если что-то требует от тебя постоянного напряжения, посмотри, действительно ли это единственный способ продолжать.','Сейчас особенно важно заметить, где ты действуешь из привычки, а где из настоящего внутреннего согласия.','Позволь себе не объяснять каждый свой выбор. Иногда ясность становится сильнее именно без лишних слов.','То, что ощущается мягче, не обязательно менее правильно. Иногда это знак, что сопротивление наконец отпускает.','Не требуй от себя мгновенного результата. Некоторые решения сначала меняют внутреннее состояние, а уже потом внешнюю реальность.','Сегодня поддержка может прийти очень просто: через паузу, разговор, совпадение, идею или спокойное ощущение «вот так».','Важно не то, насколько впечатляющим выглядит шаг, а то, возвращает ли он тебе ощущение собственного направления.','Ты можешь оставить часть вопросов открытыми. Неопределённость не отменяет того, что следующий шаг уже можно увидеть.','Когда ты выбираешь себя без борьбы, вокруг становится меньше шума и появляется место для действительно важного.'];
const endings=['Останься внимательна к первому спокойному отклику — сегодня он может оказаться точнее долгих объяснений.','Пусть это послание будет не задачей, а тихим напоминанием о том, что тебе уже доступно.','Не пытайся выполнить всё сразу. Достаточно одного действия, которое подтвердит новое состояние.','Ты не обязана знать, к чему приведёт каждый шаг. Сегодня достаточно почувствовать, что он действительно твой.','Сохрани внутри ощущение: тебе не нужно заслуживать поддержку, прежде чем позволить себе принять её.','Пусть сегодняшний выбор будет чуть ближе к тебе настоящей, даже если он не выглядит привычно.','Если сомнение вернётся, не спорь с ним. Просто снова вернись к тому, рядом с чем дыхание становится свободнее.','Сегодня можно оставить пространство для хорошего, не требуя заранее доказательств того, как именно оно придёт.','Доверься не обещанию идеального дня, а своей способности возвращаться к себе столько раз, сколько понадобится.','Иди дальше без внутренней спешки. То, что действительно твоё, не требует от тебя исчезнуть по пути.'];
const prompts=['Где сегодня мне важно выбрать себя, а не привычную реакцию?','Какой ответ уже есть во мне, если перестать искать подтверждение снаружи?','Что станет легче, если я перестану торопить результат?','Где мне нужна пауза прежде, чем сказать «да»?','Какое решение возвращает мне больше пространства внутри?','Что я могу отпустить хотя бы на сегодняшний день?','Какой маленький шаг уже ощущается правильным?','Что моё тело пытается сказать мне сейчас?','Где я могу сделать проще, не потеряв главное?','Что сегодня заслуживает моего внимания больше всего?'];
const actions=['Сделай один спокойный выбор в свою пользу и не объясняй его лишний раз.','Дай себе десять минут без телефона и прислушайся к первому внутреннему ответу.','Убери один лишний шаг, который забирает энергию, но ничего не меняет.','Не отвечай сразу там, где внутри появилось напряжение. Оставь себе паузу.','Запиши одну честную фразу о том, чего ты действительно хочешь сегодня.','Закрой один маленький незавершённый цикл и почувствуй освободившееся место.','Выбери одно действие и доведи его до конца без попытки сделать идеально.','Сделай пять медленных выдохов и только потом возвращайся к решению.','Добавь в день одну красивую деталь, которая возвращает тебя к себе.','Скажи «нет» одному необязательному расходу своей энергии.'];
const motifs=['arch','halo','veil','dawn','moon','garden','wings','stars','mist','temple'];
const symbols=['✦','✧','☾','◌','✺','❋','⋆','◇','✥','❂'];
let idx=0;const cards=[];
for(const p of profiles){for(const title of p.themes){const i=idx++;const hue=(246+i*17)%360;const hue2=(hue+28+(i%5)*7)%360;const message=`${openings[i%openings.length]} ${p.voice} Тема этого послания — ${title.toLowerCase()}: не как требование что-то срочно исправить, а как приглашение заметить, где твоя энергия уже хочет двигаться иначе. ${middles[(i*3+2)%middles.length]} ${endings[(i*7+1)%endings.length]}`;cards.push({id:i+1,angel:p.angel,seal:p.seal,tone:p.tone,title,message,insight:prompts[(i*7+3)%prompts.length],action:actions[(i*9+1)%actions.length],motif:motifs[i%motifs.length],symbol:symbols[i%symbols.length],hue,hue2,bg1:`hsl(${hue} 24% ${i%2?18:22}%)`,bg2:`hsl(${hue2} 28% ${i%3?30:36}%)`,glow:`hsl(${(hue+45)%360} 48% 72%)`});}}
let chosen=null,clarifier=null;
const todayKey=()=>new Date().toISOString().slice(0,10);const fmtDate=()=>new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long'}).format(new Date()).toUpperCase();
function shell(content){app.innerHTML=`<header class="topbar"><div class="brand"><span class="brand-sigil">✦</span><span><b>ЖИВАЯ КОЛОДА</b><small>ALYA</small></span></div><button class="icon-button" id="help" aria-label="Как пользоваться">?</button></header>${content}`;document.getElementById('help').onclick=showHelp}
function intro(){shell(`<section class="ritual intro-screen"><div class="ambient ambient-one"></div><div class="ambient ambient-two"></div><p class="eyebrow">ПОСЛАНИЕ НА ${fmtDate()}</p><h1>То, что нужно<br><em>услышать сегодня.</em></h1><p class="lead">Задай свой вопрос внутри. Не ищи правильных слов — достаточно того, что сейчас действительно волнует тебя.</p><div class="question-wrap"><textarea id="question" maxlength="180" placeholder="О чём ты хочешь спросить сегодня?"></textarea></div><button type="button" class="deck-stack" id="deck" aria-label="Прикоснуться к колоде и перемешать"><span></span><span></span><span class="card-back"><i class="wing left"></i><b>✦</b><i class="wing right"></i><small>ALYA</small></span></button><p class="deck-invitation">ПРИКОСНИСЬ К КОЛОДЕ</p><p class="quiet">Позволь первому импульсу быть достаточным.</p></section>`);document.getElementById('deck').onclick=shuffle}
function shuffle(){const q=(document.getElementById('question')?.value||'').trim();sessionStorage.setItem('alya-question',q);shell(`<section class="ritual shuffle-screen"><p class="eyebrow">ОСТАНЬСЯ НА МГНОВЕНИЕ ВНУТРИ</p><h2>Прикоснись к колоде<br><em>и позволь ей ответить.</em></h2><div class="shuffle-stage"><div class="soft-ring"></div><div class="shuffle-cards">${[0,1,2,3,4,5].map(i=>`<div class="mini-back" style="--i:${i}"><span>✦</span></div>`).join('')}</div></div><p class="quiet">Не выбирай умом. Заметь первое движение.</p></section>`);setTimeout(choose,1450)}
function choose(){shell(`<section class="ritual choose-screen"><p class="eyebrow">ТВОЁ ПОСЛАНИЕ УЖЕ РЯДОМ</p><h2>Какая карта<br><em>зовёт тебя?</em></h2><div class="choice-row">${[0,1,2].map(i=>`<button class="choice-card" data-i="${i}" aria-label="Выбрать карту"><span class="choice-symbol">${symbols[(i+new Date().getDate())%symbols.length]}</span></button>`).join('')}</div><p class="quiet">Первое движение обычно самое точное.</p></section>`);document.querySelectorAll('.choice-card').forEach(b=>b.onclick=()=>drawMain(+b.dataset.i))}
function seededPool(){let seed=[...todayKey()].reduce((a,c)=>a+c.charCodeAt(0),0);let arr=[...cards];for(let i=arr.length-1;i>0;i--){seed=(seed*9301+49297)%233280;let j=Math.floor(seed/233280*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}return arr}
function drawMain(choice){const pool=seededPool();const used=JSON.parse(localStorage.getItem('alya-used-cards')||'[]');let offset=(choice*17+new Date().getDate())%pool.length;let candidate=pool[offset];for(let k=0;k<pool.length;k++){const c=pool[(offset+k)%pool.length];if(!used.includes(c.id)){candidate=c;break}}chosen=candidate;const next=[...used.filter(id=>cards.some(c=>c.id===id)),chosen.id];if(next.length>=cards.length)next.splice(0,next.length,chosen.id);localStorage.setItem('alya-used-cards',JSON.stringify(next));localStorage.setItem('alya-main-'+todayKey(),JSON.stringify(chosen));result()}
function cardStyle(c){return `--c1:${c.bg1};--c2:${c.bg2};--glow:${c.glow};--h:${c.hue};--h2:${c.hue2}`}
function cardHTML(c,compact=false){const q=sessionStorage.getItem('alya-question')||'';return `<article class="oracle-card motif-${c.motif}${compact?' compact':''}" style="${cardStyle(c)}"><div class="card-atmosphere"></div><div class="card-frame"></div><div class="card-top"><span class="micro">ALYA · ЖИВАЯ КОЛОДА</span><span class="symbol">${c.symbol}</span></div>${q&&!compact?`<p class="asked">ТВОЙ ВОПРОС · ${escapeHtml(q)}</p>`:''}<div class="angel-presence"><span>${c.seal}</span><small>${c.angel}</small></div><h2>${c.title}</h2><div class="gold-rule"><i></i></div><p class="message">${c.message}</p><div class="soft-section"><span>УСЛЫШЬ ВНУТРИ</span><p>${c.insight}</p></div><div class="soft-section action"><span>ОСТАВЬ С СОБОЙ НА ДЕНЬ</span><p>${c.action}</p></div><footer><span>${c.tone}</span><b>✦</b></footer></article>`}
function result(){shell(`<section class="result-screen"><p class="eyebrow">ТВОЁ ПОСЛАНИЕ НА ${fmtDate()}</p>${cardHTML(chosen)}<div class="actions"><button class="primary-button" id="save">СКАЧАТЬ НА ОБОИ</button><button class="text-action" id="clarify">✦ ОТКРЫТЬ УТОЧНЕНИЕ</button></div><div id="clarifier"></div><p class="tomorrow-note">Пусть это послание останется рядом сегодня.<br>К колоде можно вернуться завтра.</p></section>`);document.getElementById('save').onclick=()=>saveCard(chosen);document.getElementById('clarify').onclick=drawClarifier}
function drawClarifier(){const key='alya-clarifier-'+todayKey();const existing=localStorage.getItem(key);if(existing)clarifier=JSON.parse(existing);else{const pool=seededPool().filter(c=>c.id!==chosen.id&&c.angel!==chosen.angel);clarifier=pool[(new Date().getDate()*7+chosen.id)%pool.length];localStorage.setItem(key,JSON.stringify(clarifier))}document.getElementById('clarifier').innerHTML=`<div class="clarifier"><div class="clarifier-heading"><span>УТОЧНЯЮЩЕЕ ПОСЛАНИЕ</span><small>Не новый вопрос. Более глубокий слой того же ответа.</small></div>${cardHTML(clarifier,true)}<button class="secondary-button" id="saveClarifier">СКАЧАТЬ ЭТУ КАРТУ</button></div>`;document.getElementById('clarify').style.display='none';document.getElementById('saveClarifier').onclick=()=>saveCard(clarifier)}
function roundedRect(ctx,x,y,w,h,r){const rr=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+rr,y);ctx.arcTo(x+w,y,x+w,y+h,rr);ctx.arcTo(x+w,y+h,x,y+h,rr);ctx.arcTo(x,y+h,x,y,rr);ctx.arcTo(x,y,x+w,y,rr);ctx.closePath()}
function wrap(ctx,text,x,y,max,line,maxLines=20){const words=text.split(/\s+/);let l='',yy=y,count=0;for(const w of words){const t=l+w+' ';if(ctx.measureText(t).width>max&&l){ctx.fillText(l.trim(),x,yy);l=w+' ';yy+=line;if(++count>=maxLines)break}else l=t}if(count<maxLines&&l)ctx.fillText(l.trim(),x,yy);return yy}
function saveCard(c){const x=canvas.getContext('2d');canvas.width=1170;canvas.height=2532;let g=x.createLinearGradient(0,0,1170,2532);g.addColorStop(0,c.bg1);g.addColorStop(.5,c.bg2);g.addColorStop(1,'#16131b');x.fillStyle=g;x.fillRect(0,0,1170,2532);const rg=x.createRadialGradient(585,500,10,585,500,650);rg.addColorStop(0,'rgba(255,239,210,.23)');rg.addColorStop(1,'rgba(255,255,255,0)');x.fillStyle=rg;x.fillRect(0,0,1170,1200);x.globalAlpha=.18;x.strokeStyle='#f3d5a0';x.lineWidth=2;for(let r=170;r<520;r+=55){x.beginPath();x.arc(585,470,r,0,Math.PI*2);x.stroke()}x.globalAlpha=1;roundedRect(x,70,70,1030,2390,42);x.strokeStyle='#c6a66e';x.lineWidth=3;x.stroke();roundedRect(x,92,92,986,2346,35);x.strokeStyle='rgba(230,205,157,.36)';x.lineWidth=1;x.stroke();x.textAlign='center';x.fillStyle='#d9bd88';x.font='24px Arial';x.fillText('ALYA · ЖИВАЯ КОЛОДА',585,180);x.font='74px Georgia';x.fillStyle='#f3e7d8';x.fillText(c.symbol,585,315);x.font='28px Georgia';x.fillStyle='rgba(243,231,216,.72)';x.fillText(c.angel,585,385);x.font='58px Georgia';x.fillStyle='#fff5e8';wrap(x,c.title,585,520,900,70,3);x.strokeStyle='#c6a66e';x.lineWidth=2;x.beginPath();x.moveTo(465,690);x.lineTo(705,690);x.stroke();x.font='34px Georgia';x.fillStyle='#f5eadf';let yy=wrap(x,c.message,585,790,850,49,15);x.fillStyle='#d5b77e';x.font='22px Arial';x.fillText('УСЛЫШЬ ВНУТРИ',585,yy+115);x.fillStyle='#f8efe7';x.font='31px Georgia';yy=wrap(x,c.insight,585,yy+175,820,44,4);x.fillStyle='#d5b77e';x.font='22px Arial';x.fillText('ОСТАВЬ С СОБОЙ НА ДЕНЬ',585,yy+115);x.fillStyle='#f8efe7';x.font='30px Georgia';wrap(x,c.action,585,yy+175,820,42,4);x.fillStyle='rgba(234,215,187,.72)';x.font='21px Arial';x.fillText('ПУСТЬ ЭТО ПОСЛАНИЕ БУДЕТ РЯДОМ СЕГОДНЯ',585,2325);const a=document.createElement('a');a.download=`ALYA-${todayKey()}-${c.id}.png`;a.href=canvas.toDataURL('image/png');a.click()}
function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function showHelp(){const old=document.getElementById('guideOverlay');if(old)return;const d=document.createElement('div');d.id='guideOverlay';d.className='overlay';d.innerHTML=`<div class="guide-dialog"><button class="close-x" id="closeGuide">×</button><p class="eyebrow">КАК БЫТЬ С КОЛОДОЙ</p><h2>Не ищи правильный способ.</h2><ol><li>Сформулируй вопрос внутри или напиши его.</li><li>Прикоснись к самой колоде и дай картам перемешаться.</li><li>Выбери по первому импульсу.</li><li>Прочитай послание целиком и заметь первую фразу, которая отозвалась.</li><li>При желании открой одно уточнение и скачай нужную карту на телефон.</li></ol><p class="quiet">Никакого архива: послание остаётся у тебя только если ты сама решишь его скачать.</p></div>`;document.body.appendChild(d);document.getElementById('closeGuide').onclick=()=>d.remove();d.onclick=e=>{if(e.target===d)d.remove()}}
const saved=localStorage.getItem('alya-main-'+todayKey());if(saved){chosen=JSON.parse(saved);result()}else intro();